#:schema node_modules/wrangler/config-schema.json
name = "okta-group-users"
main = "src/index.js"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]

[vars]
STORE_R2 = true
R2_FILENAME = "okta_groups.json"
OKTA_GROUPS = ["engineering","finance"]

[triggers]
crons = ["*/5 * * * *"] # at midnight of 1st of January

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "warp-vips"